"""change answers alternative size to 100

Revision ID: 4dd1261c8052
Revises: bdc7a5af7d0a
Create Date: 2024-06-14 18:11:12.741225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dd1261c8052'
down_revision = 'bdc7a5af7d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_column('question_no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_no', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
