"""auIncrease the length of image_url column from 255 to 1024

Revision ID: 59c27f61b918
Revises: f1806e392a59
Create Date: 2024-06-21 00:48:33.525500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c27f61b918'
down_revision = 'f1806e392a59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=255),
               type_=sa.String(length=1024),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=1024),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
