"""first migrate

Revision ID: 5a7b8614f4e3
Revises: 
Create Date: 2024-06-14 18:01:57.233004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a7b8614f4e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_column('question_no')

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('total_time')
        batch_op.drop_column('prep_time')
        batch_op.drop_column('cook_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cook_time', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('prep_time', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_time', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_no', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
