"""recommiting previous changes

Revision ID: feb9c7fde48f
Revises: d7ca5debf96b
Create Date: 2024-06-15 17:20:27.610502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb9c7fde48f'
down_revision = 'd7ca5debf96b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers',
    sa.Column('answer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.String(length=100), nullable=True),
    sa.Column('alt_letter', sa.String(length=1), nullable=True),
    sa.Column('alternative', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_table('recipes',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('recipe_name', sa.String(length=255), nullable=True),
    sa.Column('recipe_category', sa.String(length=150), nullable=True),
    sa.Column('recipe_rating', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('fat_content', sa.Float(), nullable=True),
    sa.Column('saturated_fat_content', sa.Float(), nullable=True),
    sa.Column('cholesterol_content', sa.Float(), nullable=True),
    sa.Column('sodium_content', sa.Float(), nullable=True),
    sa.Column('carbohydrate_content', sa.Float(), nullable=True),
    sa.Column('fiber_content', sa.Float(), nullable=True),
    sa.Column('sugar_content', sa.Float(), nullable=True),
    sa.Column('protein_content', sa.Float(), nullable=True),
    sa.Column('recipe_servings', sa.Float(), nullable=True),
    sa.Column('recipe_ingredient', sa.PickleType(), nullable=True),
    sa.Column('recipe_instructions', sa.PickleType(), nullable=True),
    sa.Column('cooktime_min', sa.Float(), nullable=True),
    sa.Column('preptime_min', sa.Float(), nullable=True),
    sa.Column('totaltime_min', sa.Float(), nullable=True),
    sa.Column('vata_dosha_score', sa.Integer(), nullable=True),
    sa.Column('pitta_dosha_score', sa.Integer(), nullable=True),
    sa.Column('kapha_dosha_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('connection_token', sa.String(length=12), nullable=True),
    sa.Column('dosha_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_answers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.answer_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'answer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_answers')
    op.drop_table('users')
    op.drop_table('recipes')
    op.drop_table('answers')
    # ### end Alembic commands ###
